#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
apt-get update
apt-get install software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-1.7 -y
apt-get update
apt-get install haproxy=1.7.\* -y
echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        490115-web-01 34.224.94.96:80 check
        490115-web-02 34.201.161.234:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
