#!/usr/bin/env bash
# This script displays all list of the current running processes
# It displays a user-oriented format
# Must show all processes, for all users, including those which might not have a TTY
# Show process hierarchy

ps -a -x -u -f
